<%@ Page Language="C#" MasterPageFile="~/Controle/GerenciadorNovo.master" AutoEventWireup="true" CodeFile="Importacao.aspx.cs" Inherits="Controle_Cadastro_Estado" Title="Acabamentos" %>

<asp:Content ID="Content2" ContentPlaceHolderID="cphConteudo" runat="Server">
    <script type="text/javascript">
        $(document).ready(
				function () {
				    $('#divDados').show();
				    $('#tituloCadastro').css('color', '#FFF');
				});
    </script>

    <asp:HiddenField ID="hfSecao" ClientIDMode="Static" runat="server" />
    <asp:Literal runat="server" ID="litErro"></asp:Literal>
    <h1 class="TituloPagina">
        <asp:Literal runat="server" ID="litTitulo"></asp:Literal>
    </h1>

    <h1 id="tituloCadastro" style="color: #FFF;" class="TituloSecao">Cadastro
    </h1>
    <div id="divDados" runat="server" clientidmode="Static">
        <div>

            <ul>
               
                <li runat="server" id="Li2" visible="false">
                    <asp:Button runat="server" ID="btnInserirImagens" Text="Inserir Imagens nos Produtos" OnClick="btnInserirImagens_Click" CssClass="EstiloBotao" />
                </li>

                <li style="width: 600px; position: relative;">
                    <asp:GridView ID="gvCSV" runat="server" CellPadding="3" GridLines="Vertical"
                        Width="700px" Style="font-family: 'Arial'; font-size: 12px"
                        BackColor="White" BorderColor="#999999" BorderStyle="Solid"
                        BorderWidth="0px" HeaderStyle-BorderWidth="0px" RowStyle-BorderWidth="0px" EditRowStyle-BorderWidth="0px"
                        EnableModelValidation="True">
                        <FooterStyle BackColor="#CCCCCC" />
                        <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                        <SelectedRowStyle BackColor="#000099" ForeColor="White" Font-Bold="True" />
                        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                        <AlternatingRowStyle BackColor="#F8F8FB" />
                    </asp:GridView>
                </li>
                <li>
                    <asp:FileUpload runat="server" ID="fulSiteMap" />
                </li>
                <li>
                    <asp:Button runat="server" ID="btnCarregar" Text="Clique para carregar" CssClass="EstiloBotao" OnClick="btnCarregar_Click" />
                </li>
                   <li>
                    <asp:Button runat="server" ID="btnImportar" Text="Importar" CssClass="EstiloBotao" OnClick="btnImportar_Click" />
                </li>
                <li>
                    <br />
                    <br />
                    
                   <asp:Literal runat="server" ID="litLog"></asp:Literal>
                    
                </li>
            </ul>
            <div>
                <script>
                    function imagem(caminho) {
                        var element = document.getElementById('img');
                        element.setAttribute("style", "background-image: url('" + "/ImagensHQ/" + caminho + "');")
                    }
                </script>
                <h2>Imagens</h2>
                <asp:GridView runat="server" ID="gvImagens" CellPadding="3" GridLines="Vertical"
                    Width="700px" Style="font-family: 'Arial'; font-size: 12px"
                    BackColor="White" BorderColor="#999999" BorderStyle="Solid"
                    BorderWidth="0px" HeaderStyle-BorderWidth="0px" RowStyle-BorderWidth="0px" EditRowStyle-BorderWidth="0px"
                    EnableModelValidation="True" AutoGenerateDeleteButton="false" OnRowDeleting="gvImagens_RowDeleting" AutoGenerateColumns="false">
                    <FooterStyle BackColor="#CCCCCC" />
                    <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                    <SelectedRowStyle BackColor="#000099" ForeColor="White" Font-Bold="True" />
                    <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                    <AlternatingRowStyle BackColor="#F8F8FB" />
                    <Columns>
                        <asp:TemplateField HeaderText="Imagem" SortExpression="" InsertVisible="false">
                            <ItemTemplate>
                                <span style="cursor:pointer;" onclick="imagem('<%# ((Modelos.ImagemProduto)Container.DataItem).Nome %>')"><%# ((Modelos.ImagemProduto)Container.DataItem).Nome %></span>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField>
                            <ItemTemplate>
                                <asp:LinkButton runat="server" ID="apagar" OnCommand="apagar_Command" CommandArgument="<%# ((Modelos.ImagemProduto)Container.DataItem).Nome %>" Text="Apagar" ForeColor="Red"></asp:LinkButton>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                </asp:GridView>
                <style>
                    .imagess {
                        float: right;
                        margin-right: 200px;
                        height: 500px;
                        width: 500px;
                        border: 1px solid black;
                        background-repeat:no-repeat;
                        background-size:cover;
                    }
                </style>
                <div id="img" class="imagess"></div>
                <asp:FileUpload runat="server" ID="fulImagens" AllowMultiple="true" />
                <asp:Button runat="server" ID="Button1" Text="Importar Imagens" OnClick="Button1_Click" CssClass="EstiloBotao" />
            </div>
        </div>
    </div>
</asp:Content>

